### ISSUE TITLE
Poster display issues on build 1.6 (1968)

### ISSUE THREAD

**Issue by pcanham** [xbmc/Official-Kodi-Remote-iOS#132]
Seeing display issues on iPhone 8, IOS 14.3

Seeing a visual issue since updating from 16 (1939) to 1.6 (1968)

Attaching screenshots of before upgrading and after

![1968](https://user-images.githubusercontent.com/778646/104855540-47d85300-5905-11eb-9d65-babf9d12b5ac.jpg)
![1939](https://user-images.githubusercontent.com/778646/104855544-4b6bda00-5905-11eb-8dc9-bf612e4586b0.jpg)

**Comment by heitbaum** [comment]
I concur that the tv posters in 1968 are scaled incorrectly.

**Comment by wutschel** [comment]
Thanks for sharing this feedback. Are you by chance able to build the App on your own, or are you depending on a build?

The issue is a regression caused by the fix which brought back movie posters for Kodi19 (https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/107/commits/2f8bf8806583bd9e1b7d0cb7082db52f88dd0172). I chose the wrong order of assigning images. In consequence now the posters are always winning over the banners, even if the App is configured to prefer banners for TV Shows. I will provide a fix.

**Comment by heitbaum** [comment]
@wutschel - on summer holidays at the moment. So can’t build mac stuff at the moment - left that at home. Just took my LibreELEC buildhost (lol) as it’s a busy time getting ready for LE10 :-) happy to test once the TF is there

**Comment by pcanham** [comment]
Just compiled locally a copy of

Repo: wutschel/Official-Kodi-Remote-iOS
Branch: Fix_tvshow_banners

and tested that the banners are displaying correctly on the device. So looks like the Pull request #133 has fixed the issue

**Comment by heitbaum** [comment]
@wutschel / @kambala-decapitator  - can confirm 1970 working with banners on both iPad Pro 9.7” and iPhone 12 Pro
