### ISSUE TITLE
1.6.1 crash reports

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#193]
[AppStore.tar.gz](https://github.com/xbmc/Official-Kodi-Remote-iOS/files/6129846/AppStore.tar.gz)

@wutschel

**Comment by wutschel** [comment]
At a first glance I see several crashes (5 crash log archives) related to what should be fixed now with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/188.

The other crash log archives point to 

- 3x DetailViewController (all around EPG)
- 3x NowPlaying (getActivePlayer and commitEditingStyle)
- 1x RightMenuViewController (didSelectRowAtIndexPath)
- 1x pushViewController crash (we fixed one for 1.6.1 already) 
- one crash I am not able to see where this comes from.

**Comment by wutschel** [comment]
The issues in `NowPlaying:commitEditingStyle` and `RightMenuViewController:didSelectRowAtIndexPath` can be fixed with boundary checks. I locally did this already and will provide a PR when I have more fixes added.

The issues around EPG are more difficult. To me it seems there is one potential `nil`-check missing, but the other crashes are not easily recognized. Somehow I guess this might be something around non thread-safe actions. I could create a dummy object and use `@synchronized` for accesses/functions which are reported in the crash logs.

**Comment by wutschel** [comment]
The problem with `NowPlaying:getActivePlayer` might be solved by assigning values to a variable of known type. I reworked this together with replacing `objectForKey` with modern objective c in the same method.

**Comment by wutschel** [comment]
All except two crashes now have fixes. The open ones are:
- CFjC3yXU-Hfag1-WXtDZnY.xccrashpoint (no idea where to look at)
- 5jWC7NElav745UTx2UCfS.xccrashpoint (pushViewController again, but no informative call stack)

When looking at the occurances I can see no obvious problem with these `pushViewController` calls. I only found an obsolete method calling this. The method `showRemoteController` can be removed.

**Comment by kambala-decapitator** [comment]
let's see if they keep popping up in next release
