### ISSUE TITLE
Keyboard overlays the search results

### ISSUE THREAD

**Issue by heitbaum** [xbmc/Official-Kodi-Remote-iOS#241]
Minor usability issue with the search dialog and the keyboard overlaying the results. If you click on one on the movies and then click back - you get a full screen. (There should be a Done - similar to the web page entry. Second photo)

Occurs in 2209.1

![C2F67E85-8125-4B01-B0BB-1191CF50B6D7](https://user-images.githubusercontent.com/6086324/114302114-fd80ff80-9b0a-11eb-81ed-dc824e27421e.png)

![94D627A8-027B-41A1-8D68-9B0BB2248C35](https://user-images.githubusercontent.com/6086324/114302203-581a5b80-9b0b-11eb-88d8-1a649578b6b9.png)

**Comment by wutschel** [comment]
Found a solution for this. What exactly is the correct behavior for the "Done" button? Shall just the keyboard disappear (still showing a filtered list), or shall the same happen as pressing "Cancel" next to the searchbar (cancelling search and show an unfiltered list)?

**Comment by wutschel** [comment]
Hmm, I was mainly focusing on getting the keyboard back after entering the detail view and coming back. But after re-reading your concern I think I might have misunderstood. If you just need to have "Done" to have a full view of the filtered list, you can just press "Search".

Also: What is the expected behavior for the keyboard when coming back from the detail view? I just checked with Apple´s "Pictures" App and it does only show the keyboard, if the view was left with the keyboard showing. Is this common?

Three options to implement when coming back to a view:
1. Never show keyboard, even when a search list is active (current behavior of the Remote App)
2. Always show keyboard when a search list is active 
3. Only show keyboard when this was shown before the view was initially left (kind of "last mode")

**Comment by wutschel** [comment]
My point view:
1. "Done" not needed as this does the same as "Search" for the searchbar text field.
2. Remote App should restore the keyboard visibility after coming back to the filtered list (in your example selecting a movie and pressing "back").

**Comment by heitbaum** [comment]
Hi @wutschel  - you are 100% correct.
Was way to obvious for me :-) 
please close.

**Comment by wutschel** [comment]
Thanks for the quick feedback. Let me keep this open as a reference for a fix of issue 2 (keyboard lost after entering detail view and coming back).
