### ISSUE TITLE
Safari crash

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#245]
[2021-04-12_21-24-24.1775_-0500-5b45a63d3316380a5042027f9d67ba932d81e129.crash.txt](https://github.com/xbmc/Official-Kodi-Remote-iOS/files/6320510/2021-04-12_21-24-24.1775_-0500-5b45a63d3316380a5042027f9d67ba932d81e129.crash.txt)

@wutschel

**Comment by wutschel** [comment]
It crashed when creating the SFSafariVC with `[[SFSafariViewController alloc] initWithURL:nsurl];` 

From what I found in the web this happens when the URL is invalid for Safari, eg. when the URL does not start with http:// or https:// -- see [link](https://stackoverflow.com/questions/32864287/sfsafariviewcontroller-crash-the-specified-url-has-an-unsupported-scheme). To solve this it is of course possible to check for http or https and throw and error if not present:

```
if (![url containsString:@"http://"] && ![url containsString:@"http://"]) {
    UIAlertController *alertView = [Utilities createAlertOK:NSLocalizedString(@"Error loading page", nil) message:url];
    [fromctrl presentViewController:alertView animated:YES completion:nil];
    return;
}
```

The same issue seems reported and fixed [here](https://github.com/weiran/Hackers/issues/118), but I am not into swift and am sure how this would look like in objective c.

**Comment by kambala-decapitator** [comment]
for a quick solution just wrap safari creation in `@try` / `@catch` block and show alert with exception text

**Comment by wutschel** [comment]
Thanks for the hint. Will raise a PR with following code:

```
SFSafariViewController *svc = nil;
@try {
    svc = [[SFSafariViewController alloc] initWithURL:nsurl];
} @catch (NSException *exception) {
    UIAlertController *alertView = [Utilities createAlertOK:NSLocalizedString(@"Error loading page", nil) message:url];
    [fromctrl presentViewController:alertView animated:YES completion:nil];
    return;
}
```
