### ISSUE TITLE
TF feedback: remote controls customisation

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#343]
Ability to move the remote controls to the centre or bottom. On a Pro Max it’s a lot of wasted space but it’s also nearly impossible to reach the controls with one hand. Maybe add a customized quick action bar to the very bottom for your most used buttons. Play/pause, menu, subtitles etc.

<image src="https://user-images.githubusercontent.com/1557784/123624946-e2738100-d817-11eb-96f2-3321630fb4d7.png" width="30%" />

**Comment by wutschel** [comment]
Valid point. Simplest approach would be to bottom align the whole remote or make this configurable (top/middle/bottom aligned). Would this already help?

**Comment by kambala-decapitator** [comment]
I think centering would be the golden middle.

I'll also try to summon the tester to the issue.

**Comment by DakotaONeill** [comment]
Tester has been summoned. 

Golden / ideal situation would be the middle but ability to change would be great since the scaling for each device is slightly different correct? So different users may have different experiences. But hey I’m just happy that X + screen resolutions are supported in the first place. 

I use another app for Apple Watch controlling of Kodi. They have an iOS app as well and they face a similar issue. However they have the option of that bottom space to be a virtual track pad. That’s already a feature of this Kodi app. You could have that as an alternative too. I personally don’t use it but just a thought. 

If changing position isn’t possible again a customizable quick action bar on the bottom with 3-5 buttons that an individual can set would be great. Problem there however is iOS Reachability, the accessible feature where pulling down from the “home line” might activate a button by mistake.  I use Reachability to one hand control the app currently but iOS has a time limit of how long it keeps the screen pulled down.

**Comment by wutschel** [comment]
> Tester has been summoned. 👍 

Thanks for sharing your thoughts. Yesterday I played around a bit with the remote screen. Moving the remote to (or near to) the bottom of the view is not too complicated. A bit problematic is the embedded view though (the one you can reach from the NowPlaying screen). I will try to come to a solution which allows to select top/middle/bottom alignment. Idea is something like the following image shows. We could have a possibility to change the position via a toolbar button, if there is enough space for a toolbar (if not, we do not need the option anyhow). This could be combined with https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/332 and just add a 5th toolbar button.

<a href="https://abload.de/image.php?img=bildschirmfoto2021-06dqj9f.png"><img src="https://abload.de/img/bildschirmfoto2021-06dqj9f.png" /></a>

> scaling for each device is slightly different correct?

Yes. I though of not scaling and just moving the remote, but this really looks awkward. Can anyone tell how the usability is on an iPad? The remote view must be huge on iPads.
