### ISSUE TITLE
AppStore feedback: CPU temperature

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#389]
I think it would be great if you could add a temperature display function.

**Comment by wutschel** [comment]
Looks like the API is supporting to read this. I can give this a try. But: Where should this be shown? This is a very technical information which I feel should not disturb the user interface.

**Comment by wutschel** [comment]
A quick and dirty version to show some Kodi server details I added a button named "Server Details" to the `HostManagementViewController`. This can be used to toggle the Kodi server details. The data is only reloaded after toggling, not via timer. Looks like this for my Kodi 19.3 on a VM (I guess that's why some data is not reported properly):

<a href="https://abload.de/image.php?img=simulatorscreenshot-iyskt3.png"><img src="https://abload.de/img/simulatorscreenshot-iyskt3.png" /></a>
