### ISSUE TITLE
1.8 crashes

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#401]
quite low so far!

[AppStore.tar.gz](https://github.com/xbmc/Official-Kodi-Remote-iOS/files/7271532/AppStore.tar.gz)

**Comment by wutschel** [comment]
1. First good old friend `presentViewController` is showing up once more. I really though I covered all possible cases. Not sure if find the root cause.
2. Second good old friend is related to json issues. Most possibly caused by corrupted data coming from server as we have seen this in the past.
3. New issue which I have never seen before, related to the function `sendXbmcHttp`.

**Comment by wutschel** [comment]
As far as I understood from the crashlog for the `sendXbmcHttp` case, the crash is caused by `stringWithContentsOfURL:encoding:error:` not returning back and blocking the man thread. If I should be wrong, please let me know. To work around this I prepared a change which calls this function asynchronously. I could verify this by blocking the asynchronous call with a waiting semaphore. But I would like to test this with a Kodi version that still supports receivng http commands (`xbmcCmds/xbmcHttp?command=`). Do you know what version this will be?

Draft code: https://github.com/wutschel/Official-Kodi-Remote-iOS/tree/sendxbmchttp

**Comment by wutschel** [comment]
> * First good old friend `presentViewController` is showing up once more. I really though I covered all possible cases. Not sure if find the root cause.

Found and fixed this.

**Comment by kambala-decapitator** [comment]
> As far as I understood from the crashlog for the `sendXbmcHttp` case, the crash is caused by `stringWithContentsOfURL:encoding:error:` not returning back and blocking the man thread. If I should be wrong, please let me know. To work around this I prepared a change which calls this function asynchronously. I could verify this by blocking the asynchronous call with a waiting semaphore. But I would like to test this with a Kodi version that still supports receivng http commands (`xbmcCmds/xbmcHttp?command=`). Do you know what version this will be?
> 
> Draft code: https://github.com/wutschel/Official-Kodi-Remote-iOS/tree/sendxbmchttp

yes, your conclusion looks correct to me. Added comment to the commit.

as for the Kodi version, please check https://kodi.wiki/view/JSON-RPC_API

**Comment by wutschel** [comment]
> * New issue which I have never seen before, related to the function `sendXbmcHttp`.

Fixed following your suggestion.

**Comment by wutschel** [comment]
The issue related to json processing (crash in `JSONObjectWithData:options:error`) I cannot fix. Shall we close this one and open a new issue when new crashes are reported?

**Comment by kambala-decapitator** [comment]
yes, I agree
