### ISSUE TITLE
TF feedback: unreadable text in tv shows 

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#711]
Other views are fine but tv view looks like this no matter what settings I choose. Using iPad on iOS 16 begat here but same on 15.x iPhone. Text unreadable and icons overlaid anyway. Tied changing settings but no different.

![fits1024x1024](https://user-images.githubusercontent.com/1557784/191898278-c4605853-f776-4368-be3d-ca080358862c.jpg)

**Comment by wutschel** [comment]
First, this looks like banner mode is active, but only cover images are provided. In this case the TV Show name which if part of the cover is obviously not shown properly as might be positioned at the top or the bottom ofd the image.
Second, the text shown for TV Show banners is only coming from the banners themselves -- no banner, no TV Show name. But I agree, showing the TV Shows name in case there is no banner will be an improvement.
Third, the TV Show names will be _always_ be shown when using the cover view.

Immediate try which should be done: What happens when switching to cover mode (press the button on the lower right side of the screen showing 4 horizontal bars -- not visible in your screenshot).

**Comment by kambala-decapitator** [comment]
Unfortunately, the feedback is anonymous

**Comment by wutschel** [comment]
This is how looks like for me when there are no banner provided (looks similar on iPad):
<a href="https://abload.de/image.php?img=simulatorscreenshot-ii9fzd.png"><img src="https://abload.de/img/simulatorscreenshot-ii9fzd.png" /></a>

Would be good, if the user could also delete the App fully and re-installs. Just to be sure.

**Comment by wutschel** [comment]
Found the issue. This happen when you're *not* in Dark Mode and then have TV Shows without a banner.
