### ISSUE TITLE
Search for Artist??? A possibility?

### ISSUE THREAD

**Issue by lappskij** [xbmc/Official-Kodi-Remote-iOS#93]
Thanks a lot for a great remote, but could you please add search for artist also in Album search. A lot of people have big collections like Music of the decade or other bigger collections with multiple artists and more than 500 songs in an album. The album artist is Various Artists so if you could add Artist to the existing Song search it would be awesome. Thanks a lot in advance and waiting in suspense. BR Lappskij

**Comment by kekePower** [comment]
This is an awesome suggestion. Please consider it.

Cheers,
kekePower

**Comment by wutschel** [comment]
I am not sure I understood the request fully. You ask to have an option to search for artists, in addition to album artists? As part of the Music main menu?

I am asking as there are two options to find songs of artists as you are looking -- from what I understood -- for:
1. You configure Kodi to respond/show the artists instead of album artists
2. You go for the list of all titles (to be found under the "..." button in the Music main menu), then sort by artist and use the index to jump to the desired position.
